- name: Install 1Password password manager
  community.general.homebrew_cask:
    name: 1password

- name: Install lastpass password manager
  community.general.homebrew_cask:
    name: lastpass

- name: Install Alfred productivity utility
  community.general.homebrew_cask:
    name: alfred

- name: Install miro collaboration whiteboard
  community.general.homebrew_cask:
    name: miro

- name: Install loom for screen recording
  community.general.homebrew_cask:
    name: loom

- name: Install notion
  community.general.homebrew_cask:
    name: notion

- name: Install Dropbox for online storage
  community.general.homebrew_cask:
    name: dropbox

- name: Install Google Drive
  community.general.homebrew_cask:
    name: google-drive

- name: Install mounty for NTFS volumes
  community.general.homebrew_cask:
    name: mounty

- name: Install The Unarchiver
  community.general.homebrew_cask:
    name: the-unarchiver

- name: Install App Cleaner
  community.general.homebrew_cask:
    name: appcleaner

- name: Install flycut clipboard manager
  community.general.homebrew_cask:
    name: flycut

- name: Install clocker timezone menu
  community.general.homebrew_cask:
    name: clocker
