- name: Install 1password password manager
  community.general.homebrew_cask:
    name: 1password

- name: Install lastpass password manager
  community.general.homebrew_cask:
    name: lastpass

- name: Install alfred launcher and productivity tool
  community.general.homebrew_cask:
    name: alfred

- name: Install miro collaboration whiteboard
  community.general.homebrew_cask:
    name: miro

- name: Install loom screen recorder
  community.general.homebrew_cask:
    name: loom

- name: Install ferdium messaging aggregator
  community.general.homebrew_cask:
    name: ferdium

- name: Install zoom video conferencing tool
  community.general.homebrew_cask:
    name: zoom

- name: Install notion note-taking and collaboration tool
  community.general.homebrew_cask:
    name: notion

- name: Install dropbox cloud storage
  community.general.homebrew_cask:
    name: dropbox

- name: Install google-drive cloud storage
  community.general.homebrew_cask:
    name: google-drive

- name: Install mounty NTFS volume manager
  community.general.homebrew_cask:
    name: mounty

- name: Install the-unarchiver archive extractor
  community.general.homebrew_cask:
    name: the-unarchiver

- name: Install appcleaner application uninstaller
  community.general.homebrew_cask:
    name: appcleaner

- name: Install flycut clipboard manager
  community.general.homebrew_cask:
    name: flycut

- name: Install clocker timezone menu bar tool
  community.general.homebrew_cask:
    name: clocker
