- name: Install lastpass password manager
  community.general.homebrew_cask:
    name: lastpass

- name: Install alfred launcher and productivity tool
  community.general.homebrew_cask:
    name: alfred

- name: Install miro collaboration whiteboard
  community.general.homebrew_cask:
    name: miro

- name: Install ferdium messaging aggregator
  community.general.homebrew_cask:
    name: ferdium

- name: Install notion note-taking and collaboration tool
  community.general.homebrew_cask:
    name: notion

- name: Install google-drive cloud storage
  community.general.homebrew_cask:
    name: google-drive
  environment:
    SUDO_ASKPASS: /tmp/ansible-askpass.sh

- name: Install mounty NTFS volume manager
  community.general.homebrew_cask:
    name: mounty

- name: Install the-unarchiver archive extractor
  community.general.homebrew_cask:
    name: the-unarchiver

- name: Install appcleaner application uninstaller
  community.general.homebrew_cask:
    name: appcleaner

- name: Install flycut clipboard manager
  community.general.homebrew_cask:
    name: flycut

- name: Install clocker timezone menu bar tool
  community.general.homebrew_cask:
    name: clocker
