- name: Install git source control
  community.general.homebrew:
    name: git

- name: Install git-quick-stats
  community.general.homebrew:
    name: git-quick-stats

- name: Install GitHub tools
  community.general.homebrew:
    name: gh,git-lfs,git-filter-repo,bfg
