- name: Install Docker Desktop
  community.general.homebrew_cask:
    name: docker
    state: present
  environment:
    SUDO_ASKPASS: /tmp/ansible-askpass.sh

- name: Install Docker CLI tools
  community.general.homebrew:
    name: docker-compose,docker-credential-helper

- name: Remove Colima DOCKER_HOST override if present
  ansible.builtin.blockinfile:
    path: ~/.zprofile
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR DOCKER_HOST"
    state: absent
