- name: Install rbenv ruby version manager
  community.general.homebrew:
    name: rbenv

- name: Install ruby version 3.4.7
  ansible.builtin.command: rbenv install 3.4.7
  args:
    creates: ~/.rbenv/versions/3.4.7

- name: Configure rbenv default ruby version
  ansible.builtin.command: rbenv global 3.4.7
  register: ruby_rbenv_global
  changed_when: false

- name: Configure rbenv shell integration
  ansible.builtin.blockinfile:
    create: true
    path: ~/.zshrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR RBENV"
    mode: "0644"
    block: |
      eval "$(rbenv init -)"
      export PATH="$HOME/.rbenv/versions/3.4.7/bin:$PATH"
      export PATH="$HOME/.gem/ruby/3.4.7/bin:$PATH"
