- name: Install rbenv ruby version manager
  community.general.homebrew:
    name: rbenv

- name: Install ruby-build ruby version provider
  community.general.homebrew:
    name: ruby-build
    state: latest

- name: Install ruby version 4.0.2
  ansible.builtin.command: rbenv install 4.0.2
  args:
    creates: ~/.rbenv/versions/4.0.2

- name: Configure rbenv default ruby version
  ansible.builtin.command: rbenv global 4.0.2
  register: ruby_rbenv_global
  changed_when: false

- name: Configure rbenv shell integration
  ansible.builtin.blockinfile:
    create: true
    path: ~/.zshrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR RBENV"
    mode: "0644"
    block: |
      eval "$(rbenv init -)"
      export PATH="$HOME/.rbenv/versions/4.0.2/bin:$PATH"
      export PATH="$HOME/.gem/ruby/4.0.2/bin:$PATH"
