- name: Install rbenv for ruby version management
  community.general.homebrew:
    name: rbenv

- name: Install default ruby
  ansible.builtin.command: rbenv install 3.4.7
  args:
    creates: ~/.rbenv/versions/3.4.7

- name: Set default ruby
  ansible.builtin.command: rbenv global 3.4.7
  register: ruby_rbenv_global
  changed_when: false

- name: Update .zshrc
  ansible.builtin.blockinfile:
    create: true
    path: ~/.zshrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR RBENV"
    mode: "0644"
    block: |
      eval "$(rbenv init -)"
      export PATH="$HOME/.rbenv/versions/3.4.7/bin:$PATH"
      export PATH="$HOME/.gem/ruby/3.4.7/bin:$PATH"
